#!/usr/bin/env python

## Lick (the timestamp) And Send it 'Fast edition'--> FLAS

import sys, os
import configparser
import paramiko 
import argparse
from setuptools import find_packages
from lib import connections

recon_path = os.path.dirname(os.path.abspath(__file__))
  
props = configparser.ConfigParser()
props.read(os.path.join(recon_path,'config/props.ini'))

server_dict = connections.get_servers(os.path.join(recon_path,'config/servers.ini'),props['default-server'])                                                                                                
  
cmd = ' '.join(sys.argv[1:])

stdin, stdout, stderr = server_dict['connection'].exec_command(cmd)

for line in iter(stdout.readline, ""):
    print(line, end="")
stdout.channel.recv_exit_status()                                   